<?php
/**
 * Clinic customization default keys and values.
 * Used to seed and validate clinic_customization table.
 */
return [
    // General / Logos
    'clinic_name' => 'Dr. Romarico C. Gonzales Dental Clinic',
    'logo' => 'DRCGLogo.png',           // Footer, admin login, admin create account
    'logo_nav' => 'DRCGLogo2.png',     // Client nav, admin sidebar & header
    'logo_register' => 'DRCGLogo.png', // Register page only
    // Colors (hex, no # required in value – added when outputting)
    'color_primary' => '2b8cee',
    'color_primary_dark' => '1a6cb6',
    'color_primary_light' => 'eef7ff',
    // Main page (home)
    'main_hero_line1' => 'Advanced',
    'main_hero_line2' => 'Care for a',
    'main_hero_line3' => 'Healthy Smile',
    'main_hero_badge' => '',
    'main_hero_subtext' => 'Experience modern dentistry in a sterile, calming environment. We combine clinical excellence with a gentle touch to ensure your long-term oral health.',
    'main_hero_cta_guest' => 'Set Appointment',
    'main_hero_cta_logged_in' => 'Download Our App',
    'main_hero_image' => 'Endorser1.png',
    'main_doctor_name' => 'Dr. Romarico C. Gonzales',
    'main_doctor_title' => 'Chief Dentist & Prosthodontist',
    'main_doctor_bio1' => 'With over 45 years of clinical excellence, Dr. Gonzales specializes in complex restorative procedures. He combines artistic vision with medical precision to restore function and aesthetics.',
    'main_doctor_bio2' => 'As Chief Dentist and Prosthodontist, he is dedicated to providing comprehensive care with a focus on patient comfort and long-term oral health in a stress-free environment.',
    'main_doctor_image' => 'picturenidok1.jpg',
    'main_stats_years' => '45+',
    'main_stats_smiles' => '2k+',
    'main_stats_focus' => '100%',
    'main_services_heading' => 'Our Expertise',
    'main_services_title' => 'Comprehensive Dental Solutions',
    'main_services_description' => 'From routine hygiene to complex restoration, our treatments are tailored to your specific oral health needs.',
    'main_services_watermark_word' => 'CARE',
    'main_service_card1_title' => 'Orthodontics',
    'main_service_card1_body' => 'Achieve perfect alignment with clear aligners and modern braces. We specialize in discreet corrections for all ages.',
    'main_service_card1_cta' => 'Learn more',
    'main_service_card2_title' => "Cosmetic\nDentistry",
    'main_service_card2_body' => 'Transform your smile with premium porcelain veneers, professional whitening, and aesthetic restoration techniques.',
    'main_service_card2_cta' => 'View Gallery',
    'main_service_card3_title' => 'Preventative Care',
    'main_service_card3_body' => 'Maintain lifelong oral health with comprehensive wellness exams, advanced cleanings, and digital diagnostics.',
    'main_service_card3_cta' => 'Learn more',
    'main_journey_badge' => 'Your Experience',
    'main_journey_title_before' => 'The Patient',
    'main_journey_title_accent' => 'Journey',
    'main_journey_subtitle' => 'A personalized pathway to your dream smile, from initial meeting to final reveal.',
    'main_journey_step1_title' => 'Consultation',
    'main_journey_step1_body' => 'Discuss your dental goals and concerns with our experts in a relaxed, pressure-free environment.',
    'main_journey_step1_tag' => 'Goal Alignment',
    'main_journey_step2_title' => 'Treatment Planning',
    'main_journey_step2_body' => 'Utilizing 3D imaging to create a custom roadmap and digital preview of your future results.',
    'main_journey_step2_tag' => 'Custom Roadmap',
    'main_journey_step3_title' => 'Transformation',
    'main_journey_step3_body' => 'Executing your clinical plan with precision and care, revealing your healthy, radiant new smile.',
    'main_journey_step3_tag' => 'Reveal Success',
    'main_cta_badge' => 'Your Smile Awaits',
    'main_cta_title' => 'Ready to rediscover your smile?',
    'main_cta_subtext' => 'Join thousands of happy patients who trust us with their oral health and aesthetic transformations.',
    'main_cta_button' => 'Book a Consultation',
    'main_facilities_title' => 'Clinical Facilities',
    'main_facilities_description' => 'A look at our clean, modern environment designed for your safety and comfort.',
    'main_facility_images' => '', // JSON array of {url, caption}
    // About Us
    'about_intro_heading' => 'About Us',
    'about_intro_text' => 'At Dr. Romarico C. Gonzales Dental Clinic, we blend advanced technology with compassionate care. Our mission is to create healthy, confident smiles in a clean, professional, and relaxing environment.',
    'about_hero_image' => 'Clinic2.jpg',
    'about_hero_caption_title' => 'State-of-the-art Facility',
    'about_hero_caption_text' => 'Designed for your comfort and safety with the latest dental technology.',
    'about_trusted_title' => 'Trusted Care',
    'about_trusted_text' => 'Over 2,000 happy smiles created with personalized treatment plans.',
    'about_years_number' => '45+',
    'about_years_text' => 'Years of Experience serving the community',
    'about_why_heading' => 'Why Choose Dr. Romarico C. Gonzales Dental Clinic?',
    'about_why_subtext' => 'Our patient-centered philosophy sets the standard for dental care.',
    'about_why_1_title' => 'Gentle & Painless',
    'about_why_1_text' => 'We prioritize your comfort using advanced anesthetics and minimally invasive techniques to ensure a stress-free experience.',
    'about_why_2_title' => 'Modern Technology',
    'about_why_2_text' => 'Equipped with 3D imaging and digital diagnostics, we deliver precise treatments with faster recovery times.',
    'about_why_3_title' => 'Patient-First Approach',
    'about_why_3_text' => 'We listen to your concerns and tailor every treatment plan to your unique needs and long-term health goals.',
    'about_team_doctor1_name' => 'Dr. Romarico C. Gonzales',
    'about_team_doctor1_title' => 'Chief Dentist / Prosthodontist',
    'about_team_doctor1_image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC61FPKmLLjdEd-JGu-FaDrDBqIu4jx862TB5XORXp_-jQcdzvFoZKD5ZacTgEFghcnhuHLwF4izE6cRYn2sv27PDTe8vKgLjqRwlHe3XcpvSLx7RCB-K46kXjUAAQ-NFgvDtrVeGZDhKXMj02YYolC5lxkJty40sVD8eCM1abdFFnn-OMDNE6mJBbd0OaUVj_9ozkSSxQg4z1yqRv_B-GOxYZvyKAdihO7pgMEOAyDR015Mc9fMj53j6lNT4FKM1_SWI5dXYDuIik',
    'about_team_doctor1_bio' => 'With over 20 years of clinical excellence, Dr. Gonzales specializes in complex restorative procedures. He combines artistic vision with medical precision to restore function and aesthetics.',
    'about_team_doctor1_tags' => 'Prosthodontics, Implants',
    'about_team_doctor2_name' => 'Dr. Anna Isabel Gonzales',
    'about_team_doctor2_title' => 'Pediatric & Orthodontic Specialist',
    'about_team_doctor2_image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAkpcSt3k-gpDeQrVe8UhKoH12sxTHvt8_bkraA_SXKe67CDTOfmegW9wjavtwM7afTuYuKcZK_IUzW0ip8Nt3Dx5g-cTTfIxf-RCowrPNulusuyRhKVd-pAslccj1M4krg9pvzehkDSheGN0klw1EvdTSGK1syAWN5TXpw6-dDLF5NIS7-QXk9-nLEpVKv2cL4wNPWEwFzCPp6FE8yI5RVeGxu8KEHJPrhkCDS9bL3su3JL_5owIPRYdm-GGIv5nzG_SOBJ0tmLJc',
    'about_team_doctor2_bio' => 'Dr. Anna is renowned for her gentle approach with children and anxious patients. Her expertise in orthodontics helps patients of all ages achieve perfectly aligned, confident smiles.',
    'about_team_doctor2_tags' => 'Orthodontics, Pediatric',
    'about_cta_heading' => 'Ready to smile with confidence?',
    'about_cta_subtext' => 'Schedule your comprehensive dental exam today. New patients are always welcome!',
    'about_cta_book_text' => 'Book Appointment',
    'about_cta_contact_text' => 'Contact Us Now',
    // Register
    'register_heading' => 'Create Patient Account',
    'register_subtext' => 'Join Dr. Romarico C. Gonzales Dental Clinic today to manage your dental health journey with ease.',
    'register_footer_text' => '© 2026 Dr. Romarico C. Gonzales Dental Clinic Management System. All rights reserved. Internal Use Only.',
    // Contact
    'contact_hero_heading' => "We'd love to hear from you",
    'contact_hero_subtext' => "Elevating dental practice management through clinical precision and digital curation. Our team is ready to assist your clinic's transformation.",
    'contact_address' => "Dr. Gonzales St., Tibag, Baliwag City, Bulacan",
    'contact_map_link' => 'https://maps.app.goo.gl/6hEegE4yZtBpxeWC6',
    'contact_map_embed' => 'https://www.google.com/maps?q=Dr.+Gonzales+St.,+Tibag,+Baliwag+City,+Bulacan&output=embed',
    'contact_phone' => '0998 585 7970',
    'contact_email' => 'hello@drcgdental.com',
    'contact_hours_mon_fri' => '8:00 AM - 6:00 PM',
    'contact_hours_sat' => '9:00 AM - 2:00 PM',
    'contact_hours_sun' => 'Closed',
    // Public site theme (patient-facing pages; per-tenant via clinic_customization_tenant)
    'site_favicon' => '',
    'theme_font_headline' => 'Manrope',
    'theme_font_body' => 'Inter',
    'theme_font_editorial' => 'Playfair Display',
    'theme_font_display' => 'Plus Jakarta Sans',
    'theme_base_font_px' => '16',
    'theme_line_height' => '1.6',
    'theme_heading_weight' => '800',
    'theme_radius_lg_px' => '12',
    // Services page (PatientServices.php) — treatment list/cards are managed elsewhere
    'services_page_title' => 'Our Services',
    'services_hero_badge' => 'Clinically Proven Care',
    'services_hero_title_before' => 'Our Specialized ',
    'services_hero_title_accent' => 'Services',
    'services_hero_subtitle' => 'Elevating dental wellness through clinical mastery and curated patient experiences. Discover our full spectrum of elite treatments.',
    'services_card_book_label' => 'Book Appointment',
    'services_cta_title' => 'Ready to start your journey?',
    'services_cta_subtext' => 'Join thousands of happy patients who trust us with their oral health and aesthetic transformations.',
    'services_cta_button' => 'Book Your Consultation',
    // Contact page hero (ContactUsClient.php)
    'contact_hero_badge' => 'Reach out to excellence',
    'contact_hero_title_before' => 'Get in ',
    'contact_hero_title_accent' => 'Touch.',
];
